## 1. Pauli Matrices
파울리 행렬의 아이겐밸류와 아이겐벡터를 구하시오.

In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

j=1j

sx=np.array([[0,1],[1,0]])
ex=np.linalg.eig(sx) 

sy=np.array([[0,-j],[j,0]])
ey=np.linalg.eigh(sy)

sz=np.array([[1,0],[0,-1]])
ez=np.linalg.eig(sz)

ex,ey,ez

((array([ 1., -1.]),
  array([[ 0.70710678, -0.70710678],
         [ 0.70710678,  0.70710678]])),
 (array([-1.,  1.]),
  array([[-0.70710678-0.j        , -0.70710678+0.j        ],
         [ 0.        +0.70710678j,  0.        -0.70710678j]])),
 (array([ 1., -1.]),
  array([[1., 0.],
         [0., 1.]])))

## 2. Normal Modes

In [4]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

w=np.array([[2,-1],[-1,2]])
ew=np.linalg.eig(w) 

ew

(array([3., 1.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

위에서 구한 아이겐벡터와 아이겐밸류의 의미를 설명하여라.

- 아이겐 벡터는 함수의 고유 방향을 나타내주고, 아이겐벨류는 함수를 이루는 아이겐 벡터의 최소 값의 정도를 나타내준다.